version: '3'

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf 
      - ./requirements/nginx/tools/mnurlybe.42.fr.crt:/etc/nginx/ssl/mnurlybe.42.fr.crt
      - ./requirements/nginx/tools/mnurlybe.42.fr.key:/etc/nginx/ssl/mnurlybe.42.fr.key      